### ISSUE TITLE
Error when report is not set in config

### ISSUE THREAD

**Issue by rkd77** [nitmir/policyd-rate-limit#12]
Traceback (most recent call last):
  File "/usr/local/bin/policyd-rate-limit", line 75, in <module>
    utils.clean()
  File "/usr/local/lib/python3.7/dist-packages/policyd_rate_limit/utils.py", line 339, in clean
    if len(report_text) != 0:
UnboundLocalError: local variable 'report_text' referenced before assignment

**Comment by P-EB** [comment]
Thanks for reporting

**Comment by P-EB** [comment]
Fixed in be73f3e
