### ISSUE TITLE
Bug in Debian Bookworm package : Service not starting and user not created

### ISSUE THREAD

**Issue by wouldsmina** [nitmir/policyd-rate-limit#21]
Hello
I am experiencing an issue with the policyd-rate-limit package installation in Debian 12. During installation, the service fails to start, and the policyd-rate-limit user is not being created. Upon analyzing the code in the package and comparing it to the code [in the repository](https://github.com/nitmir/policyd-rate-limit/blob/master/policyd_rate_limit/utils.py#L88) , I have noticed that the bug is fixed in the repository but not in the Debian repository.

I'm uncertain whether the failure to create the user is related to the bug that prevents the service from starting or if it is a separate issue.

Environment :

- Package Debian version: 1.0.1.1-2.1
- OS : Debian 12 (Bookworm)

Steps to Reproduce :

- Install the policyd-rate-limit package

Expected Behavior :

- The policyd-rate-limit service should start successfully.

Observed Behavior :

- The policyd-rate-limit service fails to start during installation.
- The policyd-rate-limit user is not created.

Error messages : 
```
Traceback (most recent call last):
  File "/usr/bin/policyd-rate-limit", line 36, in <module>
    config.setup()
  File "/usr/lib/python3/dist-packages/policyd_rate_limit/utils.py", line 144, in setup
    self._config = Config(config_file)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/policyd_rate_limit/utils.py", line 88, in __init__
    self._config = yaml.load(f)
                   ^^^^^^^^^^^^
TypeError: load() missing 1 required positional argument: 'Loader'
```

Resolution : 

- patch [utils.py](https://github.com/nitmir/policyd-rate-limit/blob/master/policyd_rate_limit/utils.py#L88)
- useradd policyd-rate-limit

**Comment by nitmir** [comment]
@P-EB done !

**Comment by wouldsmina** [comment]
The bug has been fixed on Debian Trixie.
